import React, { useState, useEffect } from 'react';
import { jsPDF } from 'jspdf';
import 'jspdf-autotable';
import { FileText, Download, FileBarChart, Clock, Activity } from 'lucide-react';
import api from '../api/axios';
import { toast } from 'sonner';

export default function Reports() {
  const [reports, setReports] = useState([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    const fetchReports = async () => {
      try {
        const res = await api.get('/reports');
        let data = res.data?.data || res.data?.reports || res.data;
        if (!Array.isArray(data)) data = [data];
        setReports(data);
      } catch (err) {
        toast.error('Failed to load AI reports');
      } finally {
        setLoading(false);
      }
    };
    fetchReports();
  }, []);

  const generatePDF = (report) => {
    const doc = new jsPDF();
    const date = new Date(report.created_at || Date.now()).toLocaleDateString();

    // Header
    doc.setFontSize(22);
    doc.setTextColor(40, 40, 60);
    doc.text('FraudShield AI Report', 14, 22);

    doc.setFontSize(12);
    doc.setTextColor(100, 100, 100);
    doc.text(`Generated on: ${date}`, 14, 30);
    doc.text(`Report ID: ${report.id || 'N/A'}`, 14, 36);

    // Summary block
    doc.setDrawColor(200, 200, 200);
    doc.setFillColor(245, 245, 250);
    doc.roundedRect(14, 45, 182, 35, 3, 3, 'FD');

    doc.setFontSize(14);
    doc.setTextColor(40, 40, 60);
    doc.text(report.title || 'System Analysis Report', 20, 55);

    doc.setFontSize(11);
    doc.setTextColor(80, 80, 80);
    const splitSummary = doc.splitTextToSize(report.summary || 'No summary provided.', 170);
    doc.text(splitSummary, 20, 63);

    // Data Table
    if (report.metrics && Object.keys(report.metrics).length > 0) {
      const tableData = Object.entries(report.metrics).map(([key, value]) => [
        key.replace(/_/g, ' ').toUpperCase(),
        String(value)
      ]);

      doc.autoTable({
        startY: 90,
        head: [['Metric', 'Value']],
        body: tableData,
        theme: 'grid',
        headStyles: { fillColor: [99, 102, 241] },
        styles: { fontSize: 10, cellPadding: 4 },
      });
    }

    // Footer
    const pageCount = doc.internal.getNumberOfPages();
    for (let i = 1; i <= pageCount; i++) {
      doc.setPage(i);
      doc.setFontSize(10);
      doc.setTextColor(150, 150, 150);
      doc.text(`Page ${i} of ${pageCount}`, doc.internal.pageSize.getWidth() / 2, doc.internal.pageSize.getHeight() - 10, { align: 'center' });
    }

    doc.save(`FraudShield_Report_${report.id || 'export'}.pdf`);
    toast.success('PDF downloaded successfully');
  };

  return (
    <div className="max-w-6xl space-y-6 pb-20 lg:pb-0">
      <div className="flex flex-col sm:flex-row items-start sm:items-center justify-between gap-4">
        <div>
          <h1 className="text-3xl font-bold text-white mb-1">AI Reports</h1>
          <p className="text-white/40 text-sm">Automated insights and fraud analysis</p>
        </div>
      </div>

      {loading ? (
        <div className="bg-[#111116] border border-white/5 rounded-2xl p-12 text-center">
          <div className="w-8 h-8 border-4 border-indigo-500 border-t-transparent rounded-full animate-spin mx-auto mb-4"></div>
          <p className="text-white/60">Loading reports...</p>
        </div>
      ) : reports.length === 0 ? (
        <div className="bg-[#111116] border border-white/5 rounded-2xl p-12 text-center">
          <FileBarChart className="w-12 h-12 text-white/20 mx-auto mb-4" />
          <h3 className="text-white font-medium mb-1">No Reports Available</h3>
          <p className="text-white/40 text-sm">AI reports will appear here once generated by the system.</p>
        </div>
      ) : (
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
          {reports.map((report, i) => (
            <div key={report.id || i} className="bg-[#111116] border border-white/5 rounded-2xl p-5 hover:border-indigo-500/30 transition-colors flex flex-col h-full group">
              <div className="flex items-start justify-between mb-4">
                <div className="w-10 h-10 rounded-xl bg-indigo-500/10 flex items-center justify-center text-indigo-400">
                  <FileText className="w-5 h-5" />
                </div>
                <span className="text-xs font-medium px-2.5 py-1 rounded-md bg-white/5 text-white/50 flex items-center gap-1.5">
                  <Clock className="w-3 h-3" />
                  {new Date(report.created_at || Date.now()).toLocaleDateString()}
                </span>
              </div>
              
              <h3 className="text-lg font-semibold text-white mb-2 line-clamp-1">
                {report.title || 'Fraud Analysis Report'}
              </h3>
              <p className="text-sm text-white/50 mb-6 flex-1 line-clamp-3">
                {report.summary || 'Comprehensive analysis of transaction patterns and risk metrics identified by FraudShield AI.'}
              </p>

              <div className="pt-4 border-t border-white/5 flex items-center justify-between mt-auto">
                <div className="flex items-center gap-1.5 text-xs text-white/40">
                  <Activity className="w-3.5 h-3.5" />
                  {Object.keys(report.metrics || {}).length || 4} Metrics
                </div>
                <button
                  onClick={() => generatePDF(report)}
                  className="flex items-center gap-2 text-sm font-medium text-indigo-400 hover:text-indigo-300 transition-colors"
                >
                  <Download className="w-4 h-4" /> PDF
                </button>
              </div>
            </div>
          ))}
        </div>
      )}
    </div>
  );
}
